name = "thelokals-app"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

# Environment Variables (Non-Secret)
# Update these values to match your Supabase project settings.
# For secrets, use 'wrangler pages secret put' or the Dashboard (if they don't get overwritten).
[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://gdnltvvxiychrsdzenia.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdkbmx0dnZ4aXljaHJzZHplbmlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM4MjM2NzIsImV4cCI6MjA3OTM5OTY3Mn0.LKYscrC9N4320dv0KimqqS83WKHJXQgN5Hyinw2Rua8"
NODE_VERSION = "20"