name = "web-client"
main = ".opennext/cloudflare-pages.json"
compatibility_date = "2025-12-08"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "frontend/apps/web-client/.open-next/assets"

[[build.adapters]]
adapter = "@opennextjs/cloudflare"
