name = "web-client"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next/assets"

# Force long caching for static assets (Logo)
[[headers]]
  pattern = "/*.svg"
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  pattern = "/*.ico"
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

